### ISSUE TITLE
CI calculation seems to be wrong

### ISSUE THREAD

**Issue by ferhatbilgic** [airicyu/ahp#4]
Hi, 
I think there is an error causing miscalculation of CI. 
`let ci = (avgConsistentcyMeasures - matrix.length) / 2;`
You need to divide this to (matrix.length-1) instead of '2'. I've sent a pull request but it seems like travis had failed because of the test cases and I'm assuming all of the cases and expected values has been calculated with this equation. Correct me if I'm wrong,
Regards

**Comment by airicyu** [comment]
Thanks @ferhatbilgic , I see your pull request and merged it and fixed the test case.
