### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by axelraymundo** [airicyu/ahp#5]
I'm trying to use `ahp@2.3.1` on my Strapi project but I get this error because Strapi still uses CommonJS and I cannot use `const 
 AHP = require('ahp)` 

**Workaround**: I used `ahp@2.2.2` and installed it using `yarn --ignore-engines` 
I used `--ignore-engines` to avoid this error: `error ahp@2.2.2: The engine "node" is incompatible with this module. Expected version "6 || 7 || 8 || 9 || 10 || 11". Got "14.17.0"`

My question is, how can I use version 2.3.1 to use `require` instead of `import` since I can't add `"type":"module"` on my `package.json` file.

**Comment by airicyu** [comment]
Hello @axelraymundo , understand your concern, I have fixed this and published 2.4.2 version. In 2.4.2, you should be able to use with both commonjs or ES module type.

**Comment by axelraymundo** [comment]
> Hello @axelraymundo , understand your concern, I have fixed this and published 2.4.2 version. In 2.4.2, you should be able to use with both commonjs or ES module type.

I have installed version 2.4.2 and require is working now. Thank you very much for the quick fix!
