### ISSUE TITLE
Error : Cannot find module

### ISSUE THREAD

**Issue by zvzd** [airicyu/ahp#6]
Hello, when i use "node ahp.js" it says 
internal/modules/cjs/loader.js:582
    throw err;
    ^
is there another method to run it or I actually have an error.

tried to remove node_modes and package-lock.json then running npm install and still have the same issue.

**Comment by airicyu** [comment]
@zvzd would u mind zipping ur project and send to me by my email airic.yu@gmail.com to hv a look?

**Comment by airicyu** [comment]
@zvzd or can u give me more details on the setup & usages in your code? I would like to know how to reproduce the issue.

**Comment by airicyu** [comment]
I would close this issue first becoz there is not enough details to check the issue. Please reopen it when you can provide me more info.
