### ISSUE TITLE
Working with subcriteria

### ISSUE THREAD

**Issue by harrizsb** [airicyu/ahp#7]
Hi! I'm fairly new to AHP. I looked your `wikiLeaderExample.js` samples which based on wikipedia example, but I'm kinda confused on how to work with subcriteria (e.g. [wikiCarExample](https://en.wikipedia.org/wiki/Analytic_hierarchy_process_%E2%80%93_car_example)) using this library. Could you please elaborate on how to do that? Hopefully you could create an example of `wikiCarExample.js` as well. Thanks in advance.

**Comment by airicyu** [comment]
hello @harrizsb ,

Basically the sub-criteria is just a sub-problem of the original AHP problem.
We need some ways to express the priority rating of the subscriteria against the 6 cars, and finally they will turn into the priority rating of the "Cost" in the wiki example you mentioned. right?

What you may do is that,
(1) first you can use AHP against the sub-criteria problem.
(2) and then from the result you can get back the "rankedScoreMap" or "rankedScores" which represent the ranked scores.
(3) Then when you get back to the original problem, for the criteria with subcriteria, you can just use the API
[`ahpContext.setCriteriaItemRankByGivenScores`](https://github.com/airicyu/ahp#setcriteriaitemrankbygivenscorescriterion-vector) with the scores you get from step 2.

Below is some logical code to demonstrate it

------------------
**Calculate subcriteria part:**
------------------
import AHP from 'ahp';
const ahpContext = new AHP();

ahpContext.addItems(['car1', 'car2', 'car']);
ahpContext.addCriteria(['sub1', 'sub2', 'sub3']);

ahpContext.rankCriteriaItem('sub1', [    ...   ]);
ahpContext.rankCriteriaItem('sub2', [    ...   ]);
ahpContext.rankCriteriaItem('sub3', [    ...   ]);

ahpContext.rankCriteria(
    [   ...    ]
);

const output = ahpContext.run();
// <-- from the output, get the "rankedScores"


------------------
**Calculate main problem**
------------------

import AHP from 'ahp';
const ahpContext = new AHP();

ahpContext.addItems(['car1', 'car2', 'car']);
ahpContext.addCriteria(['crit1', 'crit2', 'crit3WithSub']);

ahpContext.rankCriteriaItem('crit1', [    ...   ]);
ahpContext.rankCriteriaItem('crit2', [    ...   ]);
ahpContext.setCriteriaItemRankByGivenScores('crit3WithSub', [   ...   ]); // <--- using the rankedScores here

ahpContext.rankCriteria(
    [   ...    ]
);

const output = ahpContext.run();

---------------------------

I am not a master in AHP problem although I wrote this library tool. But this is what I can think of which is make sense to solve this problem. Hopes that can help you. Thanks!

**Comment by harrizsb** [comment]
Thanks for the answer
